#!/usr/bin/env bash
set -eux
jlpm
jlpm build:prod
python -m pip install -e . -vv --no-build-isolation
mkdir -p ~/.jupyter
cp binder/jupyter_config.json ~/.jupyter
cp ${NB_PYTHON_PREFIX}/bin/jupyter-noui ${NB_PYTHON_PREFIX}/bin/jupyter-notebook
